// Generated by https://quicktype.io
//* Previamante debes copiar la respuesta que otorgo el ThunderClient
//* View -> Command Palette -> > Paste JSON CODE
export interface IPosts {
  userId: number;
  id:     number;
  title:  string;
  body:   string;
}
